import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { astroOgImagesGenerator } from "og-images-generator/astro";
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'Letters from Blessed Seraphim',
			customCss: ['/src/fonts/font-face.css', '/src/styles/custom.css'],
			components: {
				Aside: ['src/components/holyWrit.astro'],
			},
			defaultLocale: 'en',
			locales: {
				root: {
					label: 'English',
					lang: 'en', // lang is required for root locales
				}
			},
			// social: {
			// 	github: 'https://github.com/withastro/starlight',
			// },s
			sidebar: [
				{
					label: '1961',
					items: [
						// Each slug should match a file in src/content/docs/
						{ label: '001 -Quiting Academia', link: '/letter/001/' },
					],
				},
				{
					label: '1963',
					items: [
						{ label: '002 - Discovering Orthodoxy', link: '/letter/002/' },
						{ label: '003 - Vladika John, Vladika Sava, Alison Engler', link: '/letter/003/' },
						{ label: '004 - Orthodox Faith, Saints, Dostoyevsky', link: '/letter/004/' },
						{ label: '005 - Bookstore proposal', link: '/letter/005/' },
						{ label: '006 - Apocalypse, Life after death, Gleb', link: '/letter/006/' },
						{ label: '007 - Brochure, bookstore, brotherhood', link: '/letter/007/' },
					],
				},
				{
					label: '1964',
					items: [
						{ label: '008 - Youth group, distrust of organization, money', link: '/letter/008/' },
						{ label: '009 - Gospel reading, store by cathedral, buy books', link: '/letter/009/' },
						{ label: '010 - Paid rent, kiosk, get books', link: '/letter/010/' },
						{ label: '011 - Freedom, shop preparation, atheist at talk', link: '/letter/011/' },
						{ label: '012 - Independence, financial problems', link: '/letter/012/' },
						{ label: '013 - Banking, bookcases, icons', link: '/letter/013/' },
						{ label: '014 - Money, advertising, sign', link: '/letter/014/' },
						{ label: '015 - Bookstore business & ministry', link: '/letter/015/' },
						{ label: '016 - Vladimir Tenkevitch quits, Jordanville order', link: '/letter/016/' },
						{ label: '017 - Bookstore business', link: '/letter/017/' },
						{ label: '018 - Printing on new press', link: '/letter/018/' },
						{ label: '019 - Printing, business, icons from Jordanville', link: '/letter/019/' },
						{ label: '020 - First Orthodox Word plans, business', link: '/letter/020/' },
					],
				},
				{
					label: '1965',
					items: [
						{ label: '021 - Orthodox Word article, devil attacking, ads', link: '/letter/021/' },
						{ label: '022 - Communism, Against False Union, Vladika John’s reply', link: '/letter/022/' },
						{ label: '023 - St. Mark, ecumenism, translations', link: '/letter/023/' },
					],
				},
				{
					label: '1966',
					items: [
						{ label: '024 - Printing the Orthodox Word', link: '/letter/024/' },
						{ label: '025 - Manuscripts, Archimandrite Amvrossy, Dr. Petrochko', link: '/letter/025/' },
						{ label: '026 - Much talk in the shop, serious re: Vladika John Orthdox Word', link: '/letter/026/' },
					],
				},
				{
					label: '1970',
					items: [
						{ label: '027 - Fr. Plea to not support autocephaly', link: '/letter/027/' },
						{ label: '028 - Alaskan Church, Metropolia, Bl. Herman', link: '/letter/028/' },
						{ label: '029 - Thanks for icon of St. Theodosius', link: '/letter/029/' },
						{ label: '030 - The Orthodox Word, living conditions, autocephaly, Schmemann', link: '/letter/030/' },
						{ label: '031 - Crisis year, Metropolia, Spruce Island, Blessed Herman', link: '/letter/031/' },
						{ label: '032 - Fr. Florovsky, Orthodox practice, autocephaly', link: '/letter/032/' },
						{ label: '033 - The Orthodox Word printing, living conditions, Meyendorff', link: '/letter/033/' },
						{ label: '034 - Meyendorff, autocephaly, conscience, responsibility', link: '/letter/034/' },
						{ label: '035 - Thanks for critique of Meyend.’s attack of Synod', link: '/letter/035/' },
						{ label: '036 - Ask for money for linotype', link: '/letter/036/' },
						{ label: '037 - Suspension, Iakovos/Athenagoras/Schmemann', link: '/letter/037/' },
						{ label: '038 - The Orthodox Word with Fr. M. Pomazansky on Schmemann', link: '/letter/038/' },
						{ label: '039 - Spiritual practice, preparation for baptism', link: '/letter/039/' },
						{ label: '040 - Differences between Synod and Metropolia', link: '/letter/040/' },
						{ label: '041 - Schmemann, Metropolia, Iakovos, Florovsky', link: '/letter/041/' },
						{ label: '042 - Hindu texts, peace w/Youngs, display at Ft. Ross', link: '/letter/042/' },
						{ label: '043 - Practice for children, confession, Uniates', link: '/letter/043/' },
						{ label: '044 - Convert problems, Moscow Patriarchate', link: '/letter/044/' },
						{ label: '045 - Schmemann, Meyendorff, Fr. M. joins Synod', link: '/letter/045/' },
						{ label: '046 - Thanks for money, M. Bain, Metropolia', link: '/letter/046/' },
						{ label: '047 - Thanks for donation from St. Tikhon’s Society', link: '/letter/047/' },
						{ label: '048 - Canonization of Blessed Herman, living conditions', link: '/letter/048/' },
						{ label: '049 - Service to Blessed Herman, anarchy, Hitler', link: '/letter/049/' },
						{ label: '050 - Tsar, Soviets, Meyendorff', link: '/letter/050/' },
						{ label: '051 - Metropolia, Schmemann & Meyendorff, Alaska', link: '/letter/051/' },
						{ label: '052 - Metropolia, ecumenism, betraying Orthodoxy', link: '/letter/052/' },
						{ label: '053 - Bishop Theodosius, Sergianism, Metropolia', link: '/letter/053/' },
						{ label: '054 - The Orthodox Word, living conditions, Vladika John’s repose anniversary', link: '/letter/054/' },
						{ label: '055 - Blessed Herman, coming canonization', link: '/letter/055/' },
						{ label: '056 - Canonization, Soviet bishops, Life of Blessed Herman', link: '/letter/056/' },
						{ label: '057 - Canonization report in detail, Alaskan service', link: '/letter/057/' },
						{ label: '058 - Linotype, Athenagoras/Iakovos investigation', link: '/letter/058/' },
						{ label: '059 - St. Herman reported as hippie saint, relics', link: '/letter/059/' },
						{ label: '060 - Metropolia, St. Herman, autocephaly', link: '/letter/060/' },
						{ label: '061 - Metropolia, Iakovos article, chiliasm, nihilism', link: '/letter/061/' },
						{ label: '062 - Metropolia, Communist Church, coming tonsure', link: '/letter/062/' },
						{ label: '063 - Athenagoras’ apostasy, true Orthodox publications', link: '/letter/063/' },
						{ label: '064 - Living conditions at Platina', link: '/letter/064/' },
						{ label: '065 - Tonsure, The Orthodox Word on St. Herman canonization', link: '/letter/065/' },
						{ label: '066 - Referrals to European Orthodox Missions', link: '/letter/066/' },
						{ label: '067 - Ecumenism, Catacomb Church, Metropolia', link: '/letter/067/' },
					],
				},
				{
					label: '1971',
					items: [
						{ label: '068 - Christmas crisis with Vladika Anthony, staretz game', link: '/letter/068/' },
						{ label: '069 - Tonsure, Christmas crisis, need independence', link: '/letter/069/' },
						{ label: '070 - Basic rule for prayer & daily readings', link: '/letter/070/' },
						{ label: '071 - Spark of Orthodoxy, refer Fr. Azkoul in St. Louis', link: '/letter/071/' },
						{ label: '072 - Protest treatment of Archimandrite Kyprian K.', link: '/letter/072/' },
						{ label: '073 - Tonsure, obedience spiritually illegitimate, Orthodox Word', link: '/letter/073/' },
						{ label: '074 - Vladika Anthony Ukase, Vladika John’s memory, independence', link: '/letter/074/' },
						{ label: "074.1 - Invitation to stay at Platina, Fr. Alexey's name day commemorated", link: '/letter/074-1/' },
						{ label: '075 - Jordanville trying to recruit them, stay in Platina', link: '/letter/075/' },
						{ label: '076 - “I am in terrible state.” Vladika John’s blessing', link: '/letter/076/' },
						{ label: '077 - Independence, mockery of authority, obedience', link: '/letter/077/' },
						{ label: '078 - Turkish & Communist Yokes, Sergianism', link: '/letter/078/' },
						{ label: '079 - Translations, Orthodox Word, Moscow Patriarchate', link: '/letter/079/' },
						{ label: '080 - Name of St. Herman, not St. Germain', link: '/letter/080/' },
						{ label: '081 - Name of St. Herman in unnecessary controversy', link: '/letter/081/' },
						{ label: '082 - OK to visit, but don’t tell Vladika Anthony', link: '/letter/082/' },
						{ label: '083 - Linotype, calendar, Metropolia spirit in ROCOR', link: '/letter/083/' },
						{ label: '084 - Vladika Nektary/Vladika Anthony, no contact with Vladika A.', link: '/letter/084/' },
						{ label: '084.1 - Private devotion to uncanonized saints, monarchism and modern Russia, veneration of the passion-bearing Imperial Family', link: '/letter/084-1/' },
						{ label: '085 - Services to saints, calendar, publication, plans', link: '/letter/085/' },
						{ label: "086 - Vladika Anthony's visit as peacemaker, ceasefire, Vladika Nektary", link: '/letter/086/' },
						{ label: '087 - Fr. Neketas’ visit, Mrs. Harvey, living conditions', link: '/letter/087/' },
						{ label: '088 - Monastery vs. church organization. Cover letter to...', link: '/letter/088/' },
						{ label: '089 - Rules for their monastic community if he comes', link: '/letter/089/' },
						{ label: '090 - Finish seminary, try to find inspiration at Jordanville', link: '/letter/090/' },
						{ label: '091 - Arkady ms., publications, 90% physical labor', link: '/letter/091/' },
						{ label: '092 - 6 month trial, debts, monasticism & world don’t mix', link: '/letter/092/' },
						{ label: '093 - Alexey Young Writing articles, Vladika John, Lives of Saints', link: '/letter/093/' },
						{ label: '094 - Stay in seminary', link: '/letter/094/' },
						{ label: '095 - Fr. Theodoritos’ visit, organizational view', link: '/letter/095/' },
						{ label: '096 - Nikodemos, publish-personality, American Orthodoxy', link: '/letter/096/' },
						{ label: '097 - Idea of Orthodox America, traditional bishops', link: '/letter/097/' },
						{ label: '097.1 - Request for construction supplies, fair weather in Platina', link: '/letter/097-1/' },
						{ label: '097.2 - Unofficial missionary efforts, nascent publication Nikodemos, spiritual struggle', link: '/letter/097-2/' },
						{ label: "097.3 - First issue of Nikodemus, Vladika Anthony's blessing, a foot of snow in the northen wilds", link: '/letter/097-3/' },
					],
				},
				{
					label: '1972',
					items: [
						{ label: '097.4 -New publication discussed, St. Herman Calendar', link: '/letter/097-4/' },
						{ label: '097.5 - New publication discussed, series on pre-schism England planned', link: '/letter/097-5/' },
						{ label: '097.6 - Optina Monastery publication, the staretical falsity of the literary Zossima', link: '/letter/097-6/' },
						{ label: '098 - Idea of Orthodox America, traditional bishops', link: '/letter/098/' },
						{ label: '098.1 - Publication of Nikodemus No. 2, article on Blessed Feofil, examplars of Holy Foolery', link: '/letter/098-1/' },
						{ label: "098.2 - New issue of Nikodemos, Vladika John's diocesan bulletin, a warm spring", link: '/letter/098-2/' },
						{ label: '099 - Royal Martyrs, lead type, weather', link: '/letter/099/' },
						{ label: '100 - Cut off from ecclesiastical world, “Blessed” as title', link: '/letter/100/' },
						{ label: '101 - Catacomb documents, truck broke', link: '/letter/101/' },
						{ label: '102 - True Vine, Vladika Vitaly, charismatics, feeling & inspiration', link: '/letter/102/' },
						{ label: '102.1 - Nikodemos no. 3, film review, visit from Vladika Nektary', link: '/letter/102-1/' },
						{ label: '103 - Dogma of Redemption, True Vine, independence', link: '/letter/103/' },
						{ label: '104 - No. 4, don’t let Fr. Neketas take over', link: '/letter/104/' },
						{ label: '105 - Veneration of Vladika John squashed, fighting Orthodoxу', link: '/letter/105/' },
						{ label: '106 - Celtic cause, millenium, calendar, Jordanville tragedy', link: '/letter/106/' },
						{ label: '107 - Vladika Anthony’s attitude on Vladika John, pilgrims', link: '/letter/107/' },
						{ label: '108 - Spark of fervor, charismatics, Western Saints', link: '/letter/108/' },
						{ label: '109 - Shroud, evolution, Lev Puhalo, freedom to speak', link: '/letter/109/' },
						{ label: '110 - Guidance towards monasticism, Unseen Warfare', link: '/letter/110/' },
					],
				},
				{
					label: '1973',
					items: [
						{ label: '111 - Sent back tickets to get one for Fr. Seraphim, obey', link: '/letter/111/' },
						{ label: '112 - Evolution, meeting in Seattle w/Fr. Panteleimon', link: '/letter/112/' },
						{ label: '113 - Vladika Nektary, reviving Good Tidings secretly', link: '/letter/113/' },
						{ label: '114 - Confession - Greek & Russian practice, come visit', link: '/letter/114/' },
						{ label: '115 - Repose of Vladika Savva, Vladika John Chronicle, orphaned', link: '/letter/115/' },
						{ label: '116 - Don’t print Shroud article, need research', link: '/letter/116/' },
						{ label: '117 - Fr. Panteleimon’s rejection of Shroud, science, conscience', link: '/letter/117/' },
						{ label: '118 - Vladika John’s crudeness, Church not a habit, Vladika Savva', link: '/letter/118/' },
						{ label: '119 - Vladika John relics from Vladika Savva, Life of Blessed Paisius', link: '/letter/119/' },
						{ label: '120 - Defending Alexey Young’s article on evolution', link: '/letter/120/' },
						{ label: '121 - Evolution: A rival thought pattern to Orthodoxy', link: '/letter/121/' },
						{ label: '122 - Don’t let Lev Puhalo print Dogma', link: '/letter/122/' },
						{ label: '123 - Alexey Young wrong to print Shroud article, but…', link: '/letter/123/' },
						{ label: '124 - Should not have mailed Shroud, don’t argue now', link: '/letter/124/' },
						{ label: "125 - Fr. Panteleimon's clique, evolution, Shroud, independ. labors", link: '/letter/125/' },
						{ label: '126 - Need to guide and inspire converts, vs. strictness', link: '/letter/126/' },
						{ label: '127 - Converts, theologians, struggling, don’t fear threats', link: '/letter/127/' },
						{ label: '128 - Comfort after Maggie’s death, suffering through', link: '/letter/128/' },
						{ label: '129 - Discord between Greek and Russian sides/ROCOR', link: '/letter/129/' },
						{ label: '130 - Our Greeks taking over converts, Dogma, Latinism', link: '/letter/130/' },
						{ label: '131 - Humanism, philosophy, 50% polemics in the Orthodox Word', link: '/letter/131/' },
						{ label: '132 - Fr. Ephraim, Shroud, evolution, suffering essential', link: '/letter/132/' },
						{ label: '133 - V. Anderson/seminary, Boston open letter/Alexey', link: '/letter/133/' },
						{ label: "134 - No debate, Fr. Ephraim's disservice to English-speaking Orthodoxy", link: '/letter/134/' },
						{ label: '135 - Boston & Seattle vs. Vladika John on converts, ODT', link: '/letter/135/' },
						{ label: '136 - No fighting re; evolution & Shroud, recent Fathers', link: '/letter/136/' },
						{ label: '137 - Soviet prisons, Kalomiros’ reply, ODT', link: '/letter/137/' },
						{ label: '138 - Soulless calculation, heart not mind, catacombness', link: '/letter/138/' },
						{ label: "139 - Fr. Ephraim's 3rd letter, patristic revival, academic theology", link: '/letter/139/' },
						{ label: '140 - Don’t print Acquisition without Kontzevitch’s permission', link: '/letter/140/' },
						{ label: '141 - Place for Nina Seco & Barbara McCarthy', link: '/letter/141/' },
						{ label: '142 - Science & patristic notes for evolution book', link: '/letter/142/' },
					],
				},
				{
					label: '1974',
					items: [
						{ label: '143 - Community, evolution, Genesis, Apocalypse translation', link: '/letter/143/' },
						{ label: '144 - Concerning Evolution', link: '/letter/144/' },
						{ label: '145 - Teilhard, more evolution notes', link: '/letter/145/' },
						{ label: '146 - Endure, peacemaking between Alexey and Boston', link: '/letter/146/' },
						{ label: '147 - Fragment of letter on Fr. Panteleimon and evolution', link: '/letter/147/' },
						{ label: '148 - Kalomiros’ 40-page letter, weak patristics & theology', link: '/letter/148/' },
						{ label: '149 - Patristic research on evolution to come', link: '/letter/149/' },
						{ label: '150 - Reply to Kalomiros’ “stupid evolutionism”', link: '/letter/150/' },
						{ label: '151 - Reply to evolution letter', link: '/letter/151/' },
						{ label: '152 - Scientific approach, Christian evolutionism chapter', link: '/letter/152/' },
						{ label: '153 - Avoid world and church world, spiritual zeal', link: '/letter/153/' },
						{ label: '154 - Normal American seeker, prayer rule moderation', link: '/letter/154/' },
						{ label: '155 - Same seeker, evolution research, right tone', link: '/letter/155/' },
						{ label: '156 - Asking for reply to his letter', link: '/letter/156/' },
						{ label: '157 - Spiritual counsel, get college degree first', link: '/letter/157/' },
						{ label: '158 - Taking church for granted, clergy crisis in San Francisco', link: '/letter/158/' },
						{ label: '159 - Khomiakov, Optina, Western influence, Kireyevsky', link: '/letter/159/' },
						{ label: '160 - Carnal warfare, novices, trip to San Francisco', link: '/letter/160/' },
						{ label: '161 - Self-deception, crazy converts, sinning', link: '/letter/161/' },
						{ label: '162 - Luke Walmsley’s trials', link: '/letter/162/' },
						{ label: '163 - Christian evolutionism chapter & patristic section', link: '/letter/163/' },
						{ label: '164 - Don’t try to help Maria Kraft, Boston temptation', link: '/letter/164/' },
						{ label: '165 - Christian evolutionism & patristic section', link: '/letter/165/' },
						{ label: '166 - Elder, Sobor, translations, Paul Bartlett', link: '/letter/166/' },
					],
				},
				{
					label: '1975',
					items: [
						{ label: '167 - Kalomiros, John Kraft, Kireyevsky, creationism', link: '/letter/167/' },
						{ label: '168 - Daniel Olsen: correct with out committment, Kireyevsky', link: '/letter/168/' },
						{ label: '169 - John Kraft, his mother’s trying to get rid of him', link: '/letter/169/' },
						{ label: '170 - Sobor, Solzhenitsyn, pastors keep savor of Orthodoxy', link: '/letter/170/' },
						{ label: '171 - Bulgakov, Solzhenitsyn, Paris Orthodoxy', link: '/letter/171/' },
						{ label: '172 - Kireyevsky, Sergianism, organization', link: '/letter/172/' },
						{ label: '173 - Monastery as reward, raising her boys = salvation', link: '/letter/173/' },
						{ label: '174 - Birth control, sexuality, John Kraft’s education', link: '/letter/174/' },
						{ label: '175 - News and pastoral guidance, Lenten reading', link: '/letter/175/' },
						{ label: '176 - Solzhenitsyn, Sobor, Metropolia non-communion', link: '/letter/176/' },
						{ label: '177 - Fr. Panteleimon’s rebuke of Metropolitan Philaret, group pride', link: '/letter/177/' },
						{ label: '178 - Evolution book, weak converts, Christopher Amerling', link: '/letter/178/' },
						{ label: '179 - New Valaam Academy, community, NT, ORF', link: '/letter/179/' },
						{ label: '180 - Fr. Panteleimon cut off Vladika Averky for serving with Bishop Petros', link: '/letter/180/' },
						{ label: '181 - Advice: Leaving community means spiritual trouble', link: '/letter/181/' },
						{ label: '182 - Barbara McCarthy, NT, Ingrams, Fr. Panteleimon’s hold on converts', link: '/letter/182/' },
						{ label: '183 - Soloviev, Berdyaev, Kireyevsky, Florensky, Bulgakov', link: '/letter/183/' },
						{ label: '184 - Fr. Panteleimon as only Orthodox teacher, Vladika Vitaly, “feel” of Orthodoxy', link: '/letter/184/' },
						{ label: '185 - Veneration of Western Saints, list of possible ones', link: '/letter/185/' },
						{ label: '186 - St. Callistus, calendar', link: '/letter/186/' },
						{ label: '187 - Fr. Panteleimon “mess”, Hudanish/Old Believer visit', link: '/letter/187/' },
						{ label: '188 - Blessed Augustine, Saints, Latin influence, Fr. Panteleimon’s party-line', link: '/letter/188/' },
						{ label: '189 - Despondency, college boys, sect, Vladika Averky', link: '/letter/189/' },
						{ label: '190 - Fr. Panteleimon’s anything permissible, don’t fight, politics', link: '/letter/190/' },
						{ label: '191 - Fr. Panteleimon, converts, coming schism, attack on Blessed Augustine', link: '/letter/191/' },
						{ label: '192 - Convert syndrome, oily letters, politics, don’t quit', link: '/letter/192/' },
						{ label: '193 - Fr. Panteleimon and spiritual fakery, Fr. Dudko, Vladika Averky', link: '/letter/193/' },
						{ label: '194 - Bulgakov and Florensky by Schmemann, Vladika John', link: '/letter/194/' },
						{ label: '195 - Laurence Campbell, old maidism, Old Believers, Nina/Fr. Panteleimon', link: '/letter/195/' },
						{ label: '196 - Coming to visit', link: '/letter/196/' },
						{ label: '197 - True zealots, British Saints, Fr. Panteleimon’s “expert” tone', link: '/letter/197/' },
						{ label: '198 - Thomas, trust, coming visit', link: '/letter/198/' },
						{ label: '199 - Fasting, confession, Holy Communion, suffering', link: '/letter/199/' },
						{ label: '200 - Novitiate, seminary, narrow path', link: '/letter/200/' },
						{ label: '201 - Fr. Dudko, priesthood, Life of St. Gregory of Tours', link: '/letter/201/' },
						{ label: '202 - Fr. P’s crazy convert knowing better, objectivity', link: '/letter/202/' },
						{ label: '203 - Isolation and aloofness, Orth, world for yourself', link: '/letter/203/' },
						{ label: '204 - Hudanish, categorized for Vladika Averky OW, Vladika John', link: '/letter/204/' },
					],
				},
				{
					label: '1976',
					items: [
						{ label: '205 - Sederholm, tiny groups vs. parishes, Laurence goes', link: '/letter/205/' },
						{ label: '206 - Prelest, fancy, convert opinions, Laurance and Hudansh', link: '/letter/206/' },
						{ label: '207 - Fr. Panteleimon / Bishop Petros, community, Fathers cut off by party', link: '/letter/207/' },
						{ label: '208 - Rebaptism of converts, economy, psych, insecurity', link: '/letter/208/' },
						{ label: '209 - Eugene Zavarin, evolution as faith, naturalism', link: '/letter/209/' },
						{ label: '210 - Tone, degrees in science, Haekel’s theory, Western influence', link: '/letter/210/' },
						{ label: '211 - ORF, BPV, NV Acad, grads, 5th century Gaul, St. Gregory of Tours', link: '/letter/211/' },
						{ label: '212 - Blessed Augustine vs. Patristic “experts”, love & piety', link: '/letter/212/' },
						{ label: '213 - Nina Seco Getting priest for Etna, busy-busy, Vladika Averky died', link: '/letter/213/' },
						{ label: '214 - Nina’s convert syndrome, discouraged by Vladika Averky’s death', link: '/letter/214/' },
						{ label: '215 - Laurence gone, Vladika Averky’s death, heavier burden', link: '/letter/215/' },
						{ label: '216 - Rebaptism, zeal not according to knowledge, Fr. Panteleimon fashion', link: '/letter/216/' },
						{ label: '217 - Boston letter/party, lost savor of Orthodoxy, rebaptisms', link: '/letter/217/' },
						{ label: '218 - Matthewites, Auxentios, zealotry, ecumenism', link: '/letter/218/' },
						{ label: '219 - Tests & struggles ahead, feel and love for Orthodoxy', link: '/letter/219/' },
						{ label: '220 - Right wing, helped create a monster, fragrance of Orthodoxy', link: '/letter/220/' },
						{ label: '221 - Judging one’s spiritual state, stay at Jordanville, sum. help', link: '/letter/221/' },
						{ label: '222 - Dark clouds ahead, asylum at Platina', link: '/letter/222/' },
						{ label: '223 - Fleshly sins, humility, darkening atmosphere', link: '/letter/223/' },
						{ label: '224 - Loophole in your heart, letter to Andrew Bond', link: '/letter/224/' },
						{ label: '225 - Jura Mountains, Gallic Saints, Russian book on Vladika John', link: '/letter/225/' },
						{ label: '226 - Veneration of Western Saints, rebaptisms, zealots', link: '/letter/226/' },
						{ label: '227 - Synod not breaking communion, inward freedom', link: '/letter/227/' },
						{ label: '228 - Reconcile to his bishop and priests, no fighting, respect', link: '/letter/228/' },
						{ label: '229 - Threats left & right, ROCOR on royal path, Vladika John', link: '/letter/229/' },
						{ label: '230 - Andrew Bond, moderate stand for true Orthodoxy, rebaptisms', link: '/letter/230/' },
						{ label: '231 - Written in blood, trust bishops, correctness disease', link: '/letter/231/' },
						{ label: '232 - Peace, no “extra hands”, borrowing Macarios S.', link: '/letter/232/' },
						{ label: "233 - Fr. Panteleimon's censorship, Fr. Dudko, Barbara McCarthy there", link: '/letter/233/' },
						{ label: '234 - No formal declarations on breaking communion', link: '/letter/234/' },
						{ label: '235 - No startsi, spiritual reading', link: '/letter/235/' },
						{ label: '236 - Boston authority, psychological diocese of Fr. Panteleimon', link: '/letter/236/' },
						{ label: '237 - Baptism, monasticism, obedience, come', link: '/letter/237/' },
						{ label: '238 - Not offended, disagreement deep, aloof fr. details', link: '/letter/238/' },
						{ label: '239 - Suffer, commitment, NV Academy grads off path', link: '/letter/239/' },
						{ label: '240 - Western Saints, Blessed Augustine, Vita Patrum', link: '/letter/240/' },
						{ label: '241 - Greeks in camp, narrow, “right,” double standard', link: '/letter/241/' },
						{ label: '242 - Visitors, Mary Mansur, S. Kourdakov generation', link: '/letter/242/' },
						{ label: '243 - Ordinations, St. Kyprian, disunity, moderation', link: '/letter/243/' },
					],
				},
				{
					label: '1977',
					items: [
						{ label: '243 - Ordinations, St. Kyprian, disunity, moderation', link: '/letter/243/' },
						{ label: '244 - NVA tapes, preparation for Holy Communion, San Francisco', link: '/letter/244/' },
						{ label: '245 - Ordination, weight of cross, pull to heaven pilgrims', link: '/letter/245/' },
						{ label: '246 - Saints & holy men in Calendar, bishops’ authority', link: '/letter/246/' },
						{ label: '247 - Evolution, philosophy, Kalomiros, theology, Axioms', link: '/letter/247/' },
						{ label: '248 - Evolution, age of earth, mystery of creation', link: '/letter/248/' },
						{ label: '249 - Evolution, age of earth, mystery of creation', link: '/letter/249/' },
					],
				},
				{
					label: '1978',
					items: [
						{ label: '250 - Boston influence in English, restored to communion', link: '/letter/250/' },
						{ label: '251 - Proposed publications of Lives of Saints, ODT', link: '/letter/251/' },
						{ label: '252 - Fr. Panteleimon influence subsiding, calculation, keep working', link: '/letter/252/' },
						{ label: '253 - OS schism, Moscow Patr., jurisdictions, strictness', link: '/letter/253/' },
						{ label: '254 - Suffering from politics, catacomb existence', link: '/letter/254/' },
						{ label: '255 - ROCOR reaction to fanaticism, moderation', link: '/letter/255/' },
						{ label: '256 - Lev Puhalo unbalanced opinions, superior tone, BPV', link: '/letter/256/' },
					],
				},
				{
					label: '1979',
					items: [
						{ label: '257 - Receiving Fr. Donald into RCA, married a widow', link: '/letter/257/' },
						{ label: '258 - Lev Puhalo’s attack on SAD arts, in OW,V. Averky', link: '/letter/258/' },
						{ label: '259 - May join RCA as layman, not priest, keep publishing', link: '/letter/259/' },
						{ label: '260 - Step backward to Orthodox Christianity, see Fr. Ives DuBois', link: '/letter/260/' },
						{ label: '261 - OCA & RCA intercommunion, baptism, marriage', link: '/letter/261/' },
						{ label: '262 - Timothy & Anna, Moscow Patriarchate, OCA ecumenism/modernism', link: '/letter/262/' },
						{ label: '263 - Demoniac fornication, dream attacks, joining RCA', link: '/letter/263/' },
						{ label: '264 - Baptism, believing heart, contact living tradition of Orthodoxy', link: '/letter/264/' },
						{ label: '265 - Avoid test for bishop, God’s work here, pilgrimages', link: '/letter/265/' },
						{ label: '266 - Lev Puhalo to speak against tollhouses, disrespects Orthodoxy', link: '/letter/266/' },
						{ label: '267 - Shroud, Party Headquarters, life after death/Puhalo', link: '/letter/267/' },
						{ label: '268 - Monasticism/repentance, finish college, suffering', link: '/letter/268/' },
						{ label: '269 - Fr. Herman in Greece with four letters from others, writing only on Sundays', link: '/letter/269/' },
						{ label: '270 - Fr. Chrysostomos, sobriety, no longer expect much', link: '/letter/270/' },
						{ label: '271 - Vladika Vitaly, cold pretentious, not take seriously', link: '/letter/271/' },
						{ label: '272 - Choir singing, basic humility, Etna style of parish', link: '/letter/272/' },
						{ label: '273 - Puhalo contra tollhouses, Blessed Augustine, sad, no debate, SAD', link: '/letter/273/' },
						{ label: '274 - Give up reacting to Fr. Panteleimon, Orthodoxy, of head not heart', link: '/letter/274/' },
						{ label: '275 - Sympathy for sufferings = for salvation; Akakios', link: '/letter/275/' },
						{ label: '276 - Positive attitude, not reaction; suffering Orthodoxy', link: '/letter/276/' },
						{ label: '277 - Open letter, spiritual fakery, infallibility, Vladika Andrew', link: '/letter/277/' },
						{ label: '278 - Disfavor with Boston, J.Van Deerlin, Dudko inspiration', link: '/letter/278/' },
						{ label: '279 - Party attack: SAD, Brotherhood, Jordanville, Russian v. Greeks', link: '/letter/279/' },
						{ label: '280 - History of Fr. P. and Fr. N., politics vs. Russian theology', link: '/letter/280/' },
						{ label: '281 - Fr. Dudko, Boston line, Jordanville talk, duller speaker', link: '/letter/281/' },
					],
				},
				{
					label: '1980',
					items: [
						{ label: '282 - Fr. John Lewis changing jurisdictions', link: '/letter/282/' },
						{ label: '283 - Failed as spiritual father, not Christian or caring, pride', link: '/letter/283/' },
						{ label: '284 - Gleb & Welfare Dept, want him to stay, not uproot', link: '/letter/284/' },
						{ label: '285 - More SAD attacks, no Seattle conferance, cry of anguish', link: '/letter/285/' },
						{ label: '286 - SAD attacks, no Seattle conf., tollhouse not dogma', link: '/letter/286/' },
						{ label: '287 - Puhalo scandal, Dudko, Fr. N’s conferance, heart in Orthodoxy', link: '/letter/287/' },
						{ label: '288 - Puhalo scandal, Dudko, Fr. N’s conferance, heart in Orthodoxy', link: '/letter/288/' },
						{ label: '289 - Open letter from Fr. Herman on Fr. Dudko', link: '/letter/289/' },
						{ label: '290 - Dudko & positive Gospel, suffering, PA 1981 conferance', link: '/letter/290/' },
						{ label: '291 - Fr. Hilarion’s letter, black list, attitude of Fr. N., schism', link: '/letter/291/' },
						{ label: '292 - Puhalo censored by Synod, tone, Dudko’s speech', link: '/letter/292/' },
						{ label: '293 - Search for true Orthodoxy, Santa Cruz Russ, conferance', link: '/letter/293/' },
						{ label: '294 - Catacomb Church, Dudko, Blessed Augustine v. Fr. N, definitions', link: '/letter/294/' },
						{ label: '295 - Moscow, Dudko not joining Catacomb Church, heart', link: '/letter/295/' },
						{ label: '296 - Declines PA conferance, no prayer for suffering Russians', link: '/letter/296/' },
						{ label: '297 - Deep distrust of Greeks, no public prayer, sad, schism', link: '/letter/297/' },
						{ label: '298 - Non-Orthodox Christians, Dudko, interfaith marriage', link: '/letter/298/' },
						{ label: '299 - No reply to Puhalo & Fr. N., Kalomiros at PA conferance', link: '/letter/299/' },
						{ label: '300 - SAD Appendix, West, captivity, Kalomiros’ schism', link: '/letter/300/' },
						{ label: '301 - SAD Appendix, West, captivity, Kalomiros’ schism', link: '/letter/301/' },
						{ label: '302 - SAD, Bp.Ignatius & Bp.Theophan on angels', link: '/letter/302/' },
						{ label: '303 - Synod on life after death, Puhalo, no public debate', link: '/letter/303/' },
					],
				},
				{
					label: '1981',
					items: [
						{ label: '304 - Attacks by Seattle/Boston on SAD, Moscow and grace', link: '/letter/304/' },
						{ label: '305 - Kicked us out, supercorrect, work on yourself', link: '/letter/305/' },
						{ label: '306 - Jurisdictions, grace, can’t change OCA, UCSC talk', link: '/letter/306/' },
						{ label: '307 - Genesis course, Orthodox America, evolution book', link: '/letter/307/' },
						{ label: '308 - Spiritual looking in mirror, Fr. P, monasticism', link: '/letter/308/' },
						{ label: '309 - Can’t advise his manuscript, humbly confess Orthodoxy', link: '/letter/309/' },
						{ label: '310 - Blessed Augustine, correctness, distrust of Orthodox bishops', link: '/letter/310/' },
						{ label: '311 - The Orthodox Word 96 Tavrion, Metropolitan Philaret, Moscow and grace', link: '/letter/311/' },
						{ label: '312 - Visit St. Herman Pilgrimage, seminary Basil Voytan, Tavrion', link: '/letter/312/' },
						{ label: '313 - The Orthodox Word 96, silent majority v. Boston sect, 200 at Pilgrimage', link: '/letter/313/' },
						{ label: '314 - Party at PA conferance, Tavrion, Pilgrimage success', link: '/letter/314/' },
						{ label: '315 - Forbid to publish his correspondence with Kalomiros', link: '/letter/315/' },
						{ label: '316 - Greeks dry of Christian love: humble themselves', link: '/letter/316/' },
						{ label: '317 - Henning Boston schism too deep for personal forgiveness', link: '/letter/317/' },
						{ label: '318 - The Orthodox Word not controversial, Boston became pressure group.', link: '/letter/318/' },
						{ label: '319 - Basil Voytan’s seminary classes at Platina', link: '/letter/319/' },
						{ label: '320 - The Orthodox Word 96, non-finality of Russian Church situation/grace', link: '/letter/320/' },
						{ label: '321 - Puhalo gone, Moscow, Alice in Wonderland Orthodoxy', link: '/letter/321/' },					],
				},
				{
					label: '1982',
					items: [
						{ label: '322 - Wait for free Russia, reading into Synod Decision', link: '/letter/322/' },
						{ label: '323 - Letter to a Young Spiritual Seeker', link: '/letter/323/' },
						{ label: '324 - Nina Berchier unfit for marriage, failed monastic', link: '/letter/324/' },
						{ label: '325 - Seminary training, living conditions at Platina', link: '/letter/325/' },
						{ label: '326 - John Kraft’s seminary & summer plans, floaters', link: '/letter/326/' },
						{ label: '327 - Preparing for seminary and future', link: '/letter/327/' },
						{ label: '328 - From Dr. William H. deVlaming on Fr. Seraphim\'s death', link: '/letter/328/' },
					],
				},
			],
		}),
		astroOgImagesGenerator(),
		sitemap(),
	],
	output: 'static',
});
